-- MySQL Script generated by MySQL Workbench
-- Mon Oct 25 02:13:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_TRANSPORT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_TRANSPORT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_TRANSPORT` DEFAULT CHARACTER SET utf8 ;
USE `DB_TRANSPORT` ;

-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_PUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_PUESTO` (
  `ID_Puesto` INT NOT NULL,
  `Nombre_Puesto` VARCHAR(45) NULL,
  `Descripcion_Puesto` VARCHAR(45) NULL,
  `Sueldo_Puesto` DOUBLE NULL,
  `Estado_Puesto` INT NULL,
  PRIMARY KEY (`ID_Puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_TIPO_USUARIO` (
  `ID_TipoUsuario` INT NOT NULL,
  `Nombre_TipoUsuario` VARCHAR(45) NULL,
  `Descripcion_TipoUsuario` VARCHAR(45) NULL,
  `Estado_TipoUsuario` INT NULL,
  PRIMARY KEY (`ID_TipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_USUARIO` (
  `ID_Usuario` VARCHAR(45) NOT NULL,
  `Password_Usuario` VARCHAR(45) NULL,
  `ID_TipoUsuario` INT NULL,
  PRIMARY KEY (`ID_Usuario`),
  INDEX `FK_TipoUsuario_idx` (`ID_TipoUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_TipoUsuario`
    FOREIGN KEY (`ID_TipoUsuario`)
    REFERENCES `DB_TRANSPORT`.`TB_TIPO_USUARIO` (`ID_TipoUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_EMPLEADO` (
  `ID_Empleado` INT NOT NULL,
  `Nombre1_Empleado` VARCHAR(45) NULL,
  `Nombre2_Empleado` VARCHAR(45) NULL,
  `Apellido1_Empleado` VARCHAR(45) NULL,
  `Apellido2_Empleado` VARCHAR(45) NULL,
  `NIT_Empleado` INT NULL,
  `DPI_Empleado` INT NULL,
  `Telefono_Empleado` INT NULL,
  `FechaNac_Empleado` DATE NULL,
  `Email_Empleado` VARCHAR(45) NULL,
  `ID_Puesto` INT NULL,
  `Estado_Empleado` INT NULL,
  `ID_Usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Empleado`),
  INDEX `FK_Puesto_idx` (`ID_Puesto` ASC) VISIBLE,
  INDEX `FK_UsuarioEmpleado_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `FK_Puesto`
    FOREIGN KEY (`ID_Puesto`)
    REFERENCES `DB_TRANSPORT`.`TB_PUESTO` (`ID_Puesto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_UsuarioEmpleado`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `DB_TRANSPORT`.`TB_USUARIO` (`ID_Usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_CLIENTE` (
  `ID_Cliente` INT NOT NULL,
  `Nombre1_Cliente` VARCHAR(45) NULL,
  `Nombre2_Cliente` VARCHAR(45) NULL,
  `Apellido1_Cliente` VARCHAR(45) NULL,
  `Apellido2_Cliente` VARCHAR(45) NULL,
  `ID_Usuario` VARCHAR(45) NULL,
  `NIT_Cliente` INT NULL,
  `Email_Cliente` VARCHAR(45) NULL,
  `Telefono_Cliente` INT NULL,
  `Estado_Cliente` INT NULL,
  PRIMARY KEY (`ID_Cliente`),
  INDEX `FK_UsuarioCliente_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `FK_UsuarioCliente`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `DB_TRANSPORT`.`TB_USUARIO` (`ID_Usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_TIPO_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_TIPO_PRODUCTO` (
  `ID_TipoProducto` INT NOT NULL,
  `Nombre_TipoProducto` VARCHAR(45) NULL,
  `Descripcion_TipoProducto` VARCHAR(45) NULL,
  `Estado_TipoProducto` INT NULL,
  PRIMARY KEY (`ID_TipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_DEPARTAMENTO` (
  `ID_Departamento` INT NOT NULL,
  `Nombre_Departamento` VARCHAR(45) NULL,
  `Estado_Departamento` INT NULL,
  PRIMARY KEY (`ID_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_MUNICIPIO` (
  `ID_Municipio` INT NOT NULL,
  `Nombre_Municipio` VARCHAR(45) NULL,
  `ID_Departamento` INT NULL,
  `Estado_Municipio` INT NULL,
  PRIMARY KEY (`ID_Municipio`),
  INDEX `FK_Departamento_idx` (`ID_Departamento` ASC) VISIBLE,
  CONSTRAINT `FK_Departamento`
    FOREIGN KEY (`ID_Departamento`)
    REFERENCES `DB_TRANSPORT`.`TB_DEPARTAMENTO` (`ID_Departamento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_CATEGORIA` (
  `ID_Categoria` INT NOT NULL,
  `Nombre_Categoria` VARCHAR(45) NULL,
  `Descripcion_Categoria` VARCHAR(45) NULL,
  `Estado_Categoria` INT NULL,
  `ID_Municipio` INT NULL,
  PRIMARY KEY (`ID_Categoria`),
  CONSTRAINT `FK_Municipio`
    FOREIGN KEY ()
    REFERENCES `DB_TRANSPORT`.`TB_MUNICIPIO` ()
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_PRODUCTO` (
  `ID_Producto` INT NOT NULL,
  `Nombre_Producto` VARCHAR(45) NULL,
  `Costo_Producto` DOUBLE NULL,
  `Precio_Producto` DOUBLE NULL,
  `Stock_Producto` INT NULL,
  `Descripcion_Producto` VARCHAR(100) NULL,
  `ID_TipoProducto` INT NULL,
  `ID_Categoria` INT NULL,
  `Estado_Producto` INT NULL,
  PRIMARY KEY (`ID_Producto`),
  INDEX `FK_TipoProducto_idx` (`ID_TipoProducto` ASC) VISIBLE,
  INDEX `FK_Categoria_idx` (`ID_Categoria` ASC) VISIBLE,
  CONSTRAINT `FK_TipoProducto`
    FOREIGN KEY (`ID_TipoProducto`)
    REFERENCES `DB_TRANSPORT`.`TB_TIPO_PRODUCTO` (`ID_TipoProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Categoria`
    FOREIGN KEY (`ID_Categoria`)
    REFERENCES `DB_TRANSPORT`.`TB_CATEGORIA` (`ID_Categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_ENC_FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_ENC_FACTURA` (
  `ID_EncFactura` INT NOT NULL,
  `ID_Cliente` INT NULL,
  `ID_Empleado` INT NULL,
  `FechaNac_EncFactura` DATE NULL,
  `Descripcion_EncFactura` VARCHAR(45) NULL,
  `Total_EncFactura` DOUBLE NULL,
  PRIMARY KEY (`ID_EncFactura`),
  INDEX `FK_ClienteEnc_idx` (`ID_Cliente` ASC) VISIBLE,
  INDEX `FK_EmpleadoEnc_idx` (`ID_Empleado` ASC) VISIBLE,
  CONSTRAINT `FK_ClienteEnc`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `DB_TRANSPORT`.`TB_CLIENTE` (`ID_Cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EmpleadoEnc`
    FOREIGN KEY (`ID_Empleado`)
    REFERENCES `DB_TRANSPORT`.`TB_EMPLEADO` (`ID_Empleado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_TRANSPORT`.`TB_DET_FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_TRANSPORT`.`TB_DET_FACTURA` (
  `ID_DetFactura` INT NOT NULL,
  `ID_EncFactura` INT NULL,
  `ID_Producto` INT NULL,
  `Cantidad_DetFactura` INT NULL,
  `SubTotal_DetFactura` DOUBLE NULL,
  PRIMARY KEY (`ID_DetFactura`),
  INDEX `FK_EncFactura_idx` (`ID_EncFactura` ASC) VISIBLE,
  INDEX `FK_ProductoD_idx` (`ID_Producto` ASC) VISIBLE,
  CONSTRAINT `FK_ProductoD`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `DB_TRANSPORT`.`TB_PRODUCTO` (`ID_Producto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EncFactura`
    FOREIGN KEY (`ID_EncFactura`)
    REFERENCES `DB_TRANSPORT`.`TB_ENC_FACTURA` (`ID_EncFactura`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
